#Base image with Python 3.11
FROM python:3.11-slim 

RUN apt-get update

RUN pip install \
    dagster==1.9.6 \
    dagster-graphql==1.9.6 \
    dagster-webserver==1.9.6 \
    dagster-postgres==0.25.6 \
    dagster-docker==0.25.6

# Set $DAGSTER_HOME and copy dagster instance and workspace YAML there
ENV DAGSTER_HOME=/opt/dagster/dagster_home/

RUN mkdir -p $DAGSTER_HOME

COPY fpl_project/dagster.yaml fpl_project/workspace.yaml $DAGSTER_HOME

WORKDIR $DAGSTER_HOME

