dbt_project:
  target: prod
  outputs:
    prod:
      type: postgres
      host: fpl_db
      dbname: "{{ env_var('POSTGRES_DB') }}"  
      user: "{{ env_var('POSTGRES_USER') }}"
      pass: "{{ env_var('POSTGRES_PASSWORD') }}"  
      port: "{{ env_var('POSTGRES_PORT', 5432) | int }}"  
      schema: fpl
      threads: 1
      
      
  