version: 2

sources:
  - name: stg
    description: "Schema containing staging tables"
    tables:
      - name: dates
        meta:
          dagster:
            asset_key: ["staging_dates_table"]
        description: "Staging table for date information, populated by Dagster pipeline"
        columns:
          - name: date_key
            description: "The primary key for the dimension table. A date represented in integer format."
            data_tests:
              - unique
              - not_null
          - name: date_id
            description: "A date represented in ISO format."
            data_tests:
              - unique
              - not_null
          - name: year
            description: "The year of the date_id"
            data_tests:
              - not_null
          - name: month_num
            description: "The month number of the date_id"
            data_tests:
              - valid_range:
                  min_value: 1
                  max_value: 12
          - name: month_name
            description: "The month name of the date_id"
            data_tests:
              - accepted_values:
                  values: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
          - name: day_of_month
            description: "The month day of the date_id"
            data_tests:
              - valid_range:
                  min_value: 1
                  max_value: 31
          - name: day_of_week
            description: "The week day of the date_id"
            data_tests:
              - valid_range:
                  min_value: 1
                  max_value: 7 
          - name: day_name
            description: "The day name of the date_id"
            data_tests:
              - accepted_values:
                  values: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']

      - name: teams
        meta:
          dagster:
            asset_key: ["staging_teams_table"]
        description: "Staging table for team information, populated by Dagster pipeline"
        columns:
          - name: team_key  
            description: "The primary key for the dimension table. A key represents the season followed with team id."          
            data_test:
              - unique
              - not_null
          - name: team_id
            description: "The unique ID for a team within a given season."          
            data_test:
              - unique
              - not_null
              - valid_range:
                  min_value: 1
                  max_value: 20
          - name: season
            description: "The given season the team is currently in."          
            data_test:
              - unique
              - not_null
          - name: name
            description: "The full name of the team."          
            data_test:
              - unique
              - not_null
          - name: short_name
            description: "The abbreviated name of the team."          
            data_test:
              - unique
              - not_null
          - name: strength
            description: "The overall strength of a team in a given season."          
            data_test:
              - valid_range:
                  min_value: 1
                  max_value: 5
          - name: strength_overall_home
            description: "The overall strength of a team at home in a given season."          
            data_test:
              - unique
              - not_null
          - name: strength_overall_away
            description: "The overall strength of a team away from home in a given season."          
            data_test:
              - unique
              - not_null
          - name: strength_attack_home
            description: "The overall strength of a team's attack at home in a given season."          
            data_test:
              - unique
              - not_null
          - name: strength_attack_away
            description: "The overall strength of a team's attack away from home in a given season."          
            data_test:
              - unique
              - not_null
          - name: strength_defence_home
            description: "The overall strength of a team's defence at home in a given season."          
            data_test:
              - unique
              - not_null
          - name: strength_defence_away
            description: "The overall strength of a team's defence away from home in a given season."          
            data_test:
              - unique
              - not_null
          - name: extract_dt
            description: "The overall strength of a team's defence away from home in a given season."          
            data_test:
              - unique
              - not_null
              
      - name: fixtures
        meta:
          dagster:
            asset_key: ["staging_fixtures_table"]
        description: "Staging table for fixture information, populated by Dagster pipeline"
        columns:
          - name: fixture_key  
            description: "The primary key for the dimension table. A key represents the season followed with the fixture id."          
            data_test:
              - unique
              - not_null
          - name: fixture_id  
            description: "The unique ID for a fixture within a given season."          
            data_test:
              - unique
              - not_null
              - valid_range:
                  min_value: 1
                  max_value: 380
          - name: season  
            description: "The given season the fixture is played in."          
            data_test:
              - unique
              - not_null
          - name: event  
            description: "The given gameweek the fixture is played in."          
            data_test:
              - unique
              - not_null
              - valid_range:
                  min_value: 0
                  max_value: 38
          - name: finished  
            description: "An indicator for whether the fixture is completed, and all points assigned for the match."          
            data_test:
              - accepted_values:
                  values: [True, False]
          - name: team_h  
            description: "The home team of a given fixture."          
            data_test:
              - valid_range:
                  min_value: 1
                  max_value: 20
          - name: team_a  
            description: "The away team of a given fixture."          
            data_test:
              - valid_range:
                  min_value: 1
                  max_value: 20
          - name: kickoff_time  
            description: "The exact time at when a fixture is set to kickoff. The time is represented in UTC format."          
            data_test:
              - unique
              - not_null
          - name: fixture_type  
            description: "The category that a fixture is placed into."          
            data_test:
              - not_null
          - name: extract_dt  
            description: "The date that the fixture data was extracted from the FPL api."          
            data_test:
              - not_null
      - name: players
        meta:
          dagster:
            asset_key: ["staging_player_table"]
        description: "Staging table for player information, populated by Dagster pipeline"
        columns:
          - name: player_id  
            description: "The id of a given player within a given season."          
            data_test:
              - unique
              - not_null
          - name: season  
            description: "The current season."          
            data_test:
              - not_null
          - name: first_name  
            description: "The first name of a given player."          
            data_test:
              - not_null
          - name: last_name  
            description: "The last name of a given player."          
            data_test:
              - not_null
          - name: web_name  
            description: "The assigned FPL website name of a given player."          
            data_test:
              - not_null
          - name: position  
            description: "The position of a given player."          
            data_test:
              - accepted_values:
                  values: ['Goalkeeper', 'Defender', 'Midfielder', 'Forward', 'Manager']
          - name: price  
            description: "The current price of a given player."          
            data_test:
              - not_null
              - valid_range:
                  min_value: 3
                  max_value: 100
          - name: team_id  
            description: "The current team, a given player is playing for."          
            data_test:
              - not_null
          - name: extract_dt  
            description: "The date that the player data was extracted from the FPL api."          
            data_test:
              - not_null
      - name: players_initial
        description: "Staging table for initial load of player information in slowly-changing dimension format"
        columns:
          - name: player_id  
            description: "The id of a given player within a given season."          
            data_test:
              - unique
              - not_null
          - name: season  
            description: "The current season."          
            data_test:
              - not_null
          - name: first_name  
            description: "The first name of a given player."          
            data_test:
              - not_null
          - name: last_name  
            description: "The last name of a given player."          
            data_test:
              - not_null
          - name: web_name  
            description: "The assigned FPL website name of a given player."          
            data_test:
              - not_null
          - name: position  
            description: "The position of a given player."          
            data_test:
              - accepted_values:
                  values: ['Goalkeeper', 'Defender', 'Midfielder', 'Forward', 'Manager']
          - name: price  
            description: "The current price of a given player."          
            data_test:
              - not_null
              - valid_range:
                  min_value: 3
                  max_value: 100
          - name: team_key 
            description: "The current team, a given player is playing for."          
            data_test:
              - not_null
          - name: effective_dt  
            description: "The start date that the player data was valid."          
            data_test:
              - not_null
          - name: expiry_dt  
            description: "The final date that the player data was valid."          
            data_test:
              - not_null
          - name: current_ind  
            description: "The indicator of whether the record contains the current player data."          
            data_test:
              - accepted_values:
                  values: [0,1]          
      - name: matches
        meta:
          dagster:
            asset_key: ["staging_matches_table"]
        description: "Staging table for match information, populated by Dagster pipeline"
        columns:
          - name: player_id  
            description: "The id of a given player within a given season."          
            data_test:
              - not_null
          - name: fixture_id  
            description: "The id of a given fixture within a given season."          
            data_test:
              - not_null
          - name: assists  
            description: "The number of assists a player has registered within a given fixture."          
            data_test:
              - not_null
          - name: penalties_saved  
            description: "The number of penalties a player has saved within a given fixture."          
            data_test:
              - not_null
          - name: saves  
            description: "The number of saves a player has registered within a given fixture."          
            data_test:
              - not_null
          - name: ict_index  
            description: "The ICT index a player has registered within a given fixture."          
            data_test:
              - not_null
          - name: expected_goal_involvements  
            description: "The expected goal involvements a player has registered within a given fixture."          
            data_test:
              - not_null
          - name: transfers_balance  
            description: "The net transfers of a player withen a given gameweek."          
            data_test:
              - not_null
          - name: total_points  
            description: "The total FPL points a player has registered within a given fixture."          
            data_test:
              - not_null
          - name: clean_sheets  
            description: "An indicator of whether the player has registered a clean sheet in a given fixture."          
            data_test:
              - not_null
              - valid_range:
                  min_value: 0
                  max_value: 1
          - name: penalties_missed  
            description: "The number of penalties a player has missed within a given fixture."          
            data_test:
              - not_null
          - name: bonus  
            description: "The total FPL bonus points a player has registered within a given fixture."          
            data_test:
              - not_null
          - name: starts  
            description: "An indicator of whether the player has started a given fixture."          
            data_test:
              - not_null
              - valid_range:
                  min_value: 0
                  max_value: 1
          - name: expected_goals_conceded  
            description: "The expected goals a player has conceded within a given fixture."          
            data_test:
              - not_null
          - name: selected  
            description: "The number of FPL players that has selected the player for a given fixture."          
            data_test:
              - not_null
          - name: season  
            description: "The season that the fixture is being played in."          
            data_test:
              - not_null
          - name: goals_conceded  
            description: "The number of goals a player has conceded within a given fixture."          
            data_test:
              - not_null
          - name: yellow_cards  
            description: "The number of yellow cards a player has registered within a given fixture."          
            data_test:
              - not_null
          - name: bps  
            description: "The value from the bonus points system a player has registered within a given fixture."          
            data_test:
              - not_null
          - name: expected_goals  
            description: "The expected goals a player has registered within a given fixture."          
            data_test:
              - not_null
          - name: value  
            description: "The cost of a player within a given fixture."          
            data_test:
              - not_null
          - name: transfers_in  
            description: "The number of FPL users that have transferred in a player for a given fixture."          
            data_test:
              - not_null
          - name: minutes  
            description: "The total minutes a player has played within a given fixture."          
            data_test:
              - not_null
          - name: own_goals  
            description: "The number of own goals a player has conceded within a given fixture."          
            data_test:
              - not_null
          - name: red_cards  
            description: "The number of red cards a player has registered within a given fixture."          
            data_test:
              - not_null
          - name: influence  
            description: "The influence system value a player has registered within a given fixture."          
            data_test:
              - not_null
          - name: expected_assists  
            description: "The expected assists a player has registered within a given fixture."          
            data_test:
              - not_null
          - name: transfers_out  
            description: "The number of FPL users that have transferred out a player for a given fixture."          
            data_test:
              - not_null
          - name: extract_dt  
            description: "The extraction date of the match data for a given fixture."          
            data_test:
              - not_null
          - name: goals_scored  
            description: "The number of goals a player has scored within a given fixture."          
            data_test:
              - not_null
          - name: threat  
            description: "The threat system value a player has registered within a given fixture."          
            data_test:
              - not_null
          - name: creativity  
            description: "The creativity system value a player has registered within a given fixture."          
            data_test:
              - not_null
          - name: mng_win  
            description: "The team win points a manager has scored within a given fixture."          
            data_test:
              - not_null
          - name: mng_draw  
            description: "The team draw points a manager has scored within a given fixture."          
            data_test:
              - not_null
          - name: mng_loss  
            description: "The team loss points a manager has scored within a given fixture."          
            data_test:
              - not_null
          - name: mng_underdog_win  
            description: "The underdog team win indicator a manager has registered within a given fixture."          
            data_test:
              - not_null
          - name: mng_underdog_draw  
            description: "The underdog team draw indicator a manager has registered within a given fixture."          
            data_test:
              - not_null
          - name: mng_clean_sheets  
            description: "The clean sheet points a manager has registered within a given fixture."          
            data_test:
              - not_null
          - name: mng_goals_scored  
            description: "The goals scoared by a manager's team within a given fixture. Players will only have 0 as a value for this feature."          
            data_test:
              - not_null